#!/usr/bin/env python3
"""
Daily Order Summary — E-commerce AI Employee (Silver Tier)

Generates an 8 PM daily briefing of store activity and writes it to
/Briefings/DAILY_YYYY-MM-DD.md, then updates Dashboard.md.

Schedule via Windows Task Scheduler (run setup_scheduler.py once to register).

Usage:
    python daily_summary.py --vault E:/AI_Employee_Vault
    python daily_summary.py --vault E:/AI_Employee_Vault --dry-run
"""

import argparse
import json
import re
from datetime import date, datetime
from pathlib import Path


def count_folder(folder: Path, pattern: str = "ORDERS*.md") -> tuple[int, float]:
    total_orders, total_rev = 0, 0.0
    for md in folder.glob(pattern):
        text = md.read_text(encoding="utf-8", errors="ignore")
        m = re.search(r"order_count:\s*(\d+)", text)
        r = re.search(r"total_revenue:\s*\$?([\d.]+)", text)
        if m:
            total_orders += int(m.group(1))
        if r:
            total_rev += float(r.group(1))
    return total_orders, total_rev


def count_emails(folder: Path) -> int:
    return len(list(folder.glob("EMAIL_*.md")))


def count_pending_approvals(folder: Path) -> int:
    return len(list(folder.glob("*.md")))


def load_monthly_goal(vault: Path) -> float:
    goals_file = vault / "Business_Goals.md"
    if not goals_file.exists():
        return 0.0
    text = goals_file.read_text(encoding="utf-8", errors="ignore")
    m = re.search(r"Monthly goal:\s*\$?([\d,]+)", text)
    if m:
        return float(m.group(1).replace(",", ""))
    return 0.0


def generate_briefing(vault: Path) -> str:
    today = date.today()
    today_str = today.strftime("%Y-%m-%d")
    month_str = today.strftime("%Y-%m")
    now = datetime.now().strftime("%Y-%m-%d %H:%M")

    inbox = vault / "Inbox"
    needs_action = vault / "Needs_Action"
    done = vault / "Done"
    pending_approval = vault / "Pending_Approval"

    inbox_orders, inbox_rev = count_folder(inbox)
    today_done = len(list(done.glob(f"ORDERS*{today_str}*.md")))
    month_done_orders, month_done_rev = count_folder(done, f"ORDERS*{month_str}*.md")
    _, na_rev = count_folder(needs_action)
    total_month_rev = month_done_rev + inbox_rev + na_rev

    monthly_goal = load_monthly_goal(vault)
    goal_pct = (total_month_rev / monthly_goal * 100) if monthly_goal else 0

    emails_pending = count_emails(needs_action)
    approvals_pending = count_pending_approvals(pending_approval)
    needs_action_count = len(list(needs_action.glob("*.md")))

    # Trend emoji
    if goal_pct >= 80:
        trend = "On track"
    elif goal_pct >= 50:
        trend = "Progressing"
    else:
        trend = "Needs attention"

    briefing = f"""---
type: daily_summary
generated: {now}
date: {today_str}
---

# Daily Store Briefing — {today.strftime("%B %d, %Y")}

## Revenue Today
- **Orders Completed**: {today_done}
- **Month-to-Date Revenue**: ${total_month_rev:.2f}
- **Monthly Goal**: ${monthly_goal:.2f} ({goal_pct:.0f}%)
- **Status**: {trend}

## Order Queue
| Location | Count |
|----------|-------|
| Inbox (awaiting fulfilment) | {inbox_orders} |
| Needs Action | {needs_action_count} |
| Pending Approvals | {approvals_pending} |

## Customer Emails
- **Unanswered emails in /Needs_Action/**: {emails_pending}
- **Replies awaiting approval**: {len(list(pending_approval.glob("EMAIL_REPLY_*.md")))}

## Actions Required
"""

    actions = []
    if emails_pending > 0:
        actions.append(f"- [ ] Process {emails_pending} customer email(s) using `email-responder` skill")
    if approvals_pending > 0:
        actions.append(f"- [ ] Review {approvals_pending} pending approval(s) in /Pending_Approval/")
    if needs_action_count > 0:
        actions.append(f"- [ ] Clear /Needs_Action/ ({needs_action_count} item(s))")
    if inbox_orders > 0:
        actions.append(f"- [ ] Fulfil {inbox_orders} order(s) in /Inbox/")
    if not actions:
        actions.append("- All clear. Nothing pending.")

    briefing += "\n".join(actions)
    briefing += f"\n\n---\n*Generated by AI Employee at {now}*\n"
    return briefing


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--vault", default="E:/AI_Employee_Vault")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    vault = Path(args.vault)
    briefings_dir = vault / "Briefings"
    briefings_dir.mkdir(exist_ok=True)

    content = generate_briefing(vault)
    out_path = briefings_dir / f"DAILY_{date.today().strftime('%Y-%m-%d')}.md"

    if args.dry_run:
        print("[DRY RUN] Would write:")
        print(content)
    else:
        out_path.write_text(content, encoding="utf-8")
        print(f"[OK] Daily briefing written: {out_path}")

        # Also update Dashboard
        try:
            import subprocess, sys
            updater = Path("E:/AI_Employee_Vault/.claude/skills/dashboard-updater/scripts/update_dashboard.py")
            subprocess.run([sys.executable, str(updater), "--vault", str(vault)], check=True)
        except Exception as e:
            print(f"[WARN] Dashboard update failed: {e}")


if __name__ == "__main__":
    main()
